version: "3"
services:
  zabbix-agent2:
    image: zabbix/zabbix-agent2
    environment:
      - ZBX_HOSTNAME=
      - ZBX_SERVER_HOST=
      - ZBX_ACTIVE_ALLOW=true
      - ZBX_PASSIVE_ALLOW=true
      - ZBX_ENABLEPERSISTENTBUFFER=true
      - ZBX_PERSISTENTBUFFERPERIOD=6h
      - ZBX_TLSCONNECT=psk
      - ZBX_TLSACCEPT=psk
      - ZBX_TLSPSKIDENTITY=
      - ZBX_TLSPSKFILE=/var/lib/zabbix/enc/psk.key
#      - ZBX_DEBUGLEVEL=4
    volumes:
      - ./zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d
      - ./enc:/var/lib/zabbix/enc
      - ./buffer:/var/lib/zabbix/buffer
    restart: unless-stopped
